#
# Functions for pov-simple-backup
#

pending=""

emit() {
    if [ -n "$pending" ]; then
        printf "%s" "$pending"
        pending=""
    fi
    printf '%s\n' "$*"
}

prefix() {
    pending="$*"
}

separator() {
    prefix "
"
}

generate() {
    emit "#
# pov-simple-backup configuration for $(hostname -f)
#
# Generated by pov-simple-backup on $(date +"%Y-%m-%d %H:%M:%S")
#"

    separator

    emit "back_up /etc
back_up /root
back_up /usr/local
back_up /var/cache/debconf/config.dat
back_up_dpkg_selections"

    separator

    test -x /usr/bin/psql && emit "back_up_postgresql"
    test -x /usr/bin/mysql && emit "back_up_mysql"

    separator

    emit "generate_checksums"

    separator

    emit "clean_up_old_backups 14"

    separator

    emit "##copy_backup_to backups@backups.pov.lt:/backups/$(hostname)/"
}
